In [1]:
import pandas as pd 
from numpy import * 
import numpy as np 
import warnings 
warnings.filterwarnings("ignore") 
from sklearn.preprocessing import LabelEncoder
from sklearn import datasets, linear_model 
from sklearn.metrics import mean_squared_error, r2_score 
from sklearn import metrics 
from sklearn.model_selection import train_test_split 
from sklearn import neighbors 
from sklearn import svm 
from sklearn.pipeline import Pipeline 
import pickle 
from sklearn import tree 

In [2]:
data = pd.read_csv('/home/pragya/project/newenv/dataset/train dataset.csv') 

data= data.drop('Gender', 1)
data=data.drop('Age',1)
array = data.values 
data
#print(data)
#print(array)

openness  neuroticism  conscientiousness  agreeableness  extraversion  \
0           7            4                  7              3             2   
1           4            5                  4              6             6   
2           7            6                  4              5             5   
3           5            6                  7              4             3   
4           7            4                  6              5             4   
..        ...          ...                ...            ...           ...   
704         4            5                  6              6             1   
705         6            3                  1              5             5   
706         5            2                  3              6             1   
707         5            6                  5              7             5   
708         5            5                  7              6             5   

    Personality (Class label)  
0                 extraverted  
1                     serious  
2                  dependable  
3                 extraverted  
4                      lively  
..                        ...  
704               responsible  
705                dependable  
706                   serious  
707               extraverted  
708               extraverted  

[709 rows x 6 columns]

In [3]:
'''for i in range(len(array)): 
    if array[i][0] == "Male": 
        array[i][0] = 1 
    else: 
        array[i][0] = 0'''

'for i in range(len(array)): \n    if array[i][0] == "Male": \n        array[i][0] = 1 \n    else: \n        array[i][0] = 0'

In [4]:
array


array([[7, 4, 7, 3, 2, 'extraverted'],
       [4, 5, 4, 6, 6, 'serious'],
       [7, 6, 4, 5, 5, 'dependable'],
       ...,
       [5, 2, 3, 6, 1, 'serious'],
       [5, 6, 5, 7, 5, 'extraverted'],
       [5, 5, 7, 6, 5, 'extraverted']], dtype=object)

In [5]:
df = pd.DataFrame(array) 
print(df.head()) 

   0  1  2  3  4            5
0  7  4  7  3  2  extraverted
1  4  5  4  6  6      serious
2  7  6  4  5  5   dependable
3  5  6  7  4  3  extraverted
4  7  4  6  5  4       lively


In [6]:
data.isnull().sum()

openness                     0
neuroticism                  0
conscientiousness            0
agreeableness                0
extraversion                 0
Personality (Class label)    0
dtype: int64

In [7]:
maindf = df[[0, 1, 2, 3, 4]] 
mainarray = maindf.values 
print(mainarray) 
maindf

[[7 4 7 3 2]
 [4 5 4 6 6]
 [7 6 4 5 5]
 ...
 [5 2 3 6 1]
 [5 6 5 7 5]
 [5 5 7 6 5]]


0  1  2  3  4
0    7  4  7  3  2
1    4  5  4  6  6
2    7  6  4  5  5
3    5  6  7  4  3
4    7  4  6  5  4
..  .. .. .. .. ..
704  4  5  6  6  1
705  6  3  1  5  5
706  5  2  3  6  1
707  5  6  5  7  5
708  5  5  7  6  5

[709 rows x 5 columns]

In [8]:
temp = df[5] 
print(temp)

0      extraverted
1          serious
2       dependable
3      extraverted
4           lively
          ...     
704    responsible
705     dependable
706        serious
707    extraverted
708    extraverted
Name: 5, Length: 709, dtype: object


In [9]:
train_y = temp.values 
print(train_y) 
print(mainarray) 

['extraverted' 'serious' 'dependable' 'extraverted' 'lively' 'lively'
 'extraverted' 'extraverted' 'dependable' 'lively' 'serious' 'extraverted'
 'lively' 'dependable' 'responsible' 'extraverted' 'serious' 'dependable'
 'responsible' 'extraverted' 'responsible' 'extraverted' 'responsible'
 'serious' 'serious' 'dependable' 'extraverted' 'extraverted' 'lively'
 'lively' 'extraverted' 'extraverted' 'dependable' 'lively' 'serious'
 'lively' 'responsible' 'responsible' 'dependable' 'serious' 'dependable'
 'extraverted' 'serious' 'extraverted' 'dependable' 'dependable'
 'responsible' 'serious' 'lively' 'lively' 'extraverted' 'extraverted'
 'serious' 'extraverted' 'lively' 'lively' 'extraverted' 'dependable'
 'lively' 'lively' 'responsible' 'extraverted' 'responsible' 'dependable'
 'serious' 'serious' 'responsible' 'dependable' 'responsible' 'dependable'
 'extraverted' 'extraverted' 'responsible' 'dependable' 'responsible'
 'serious' 'extraverted' 'dependable' 'lively' 'lively' 'extraverted'


In [10]:
#train_y = temp.values
#train_y

In [11]:
for i in range(len(train_y)): 
    train_y[i] = str(train_y[i]) 

In [12]:
lables = ["Logistic Regression", "SVM", "Decision Tree"]

In [13]:
from sklearn.linear_model import LogisticRegression
models = [linear_model.LogisticRegression(multi_class='auto', solver='newton-cg', max_iter=1000),svm.SVC(kernel="poly"), tree.DecisionTreeClassifier()] 


In [14]:
#mul_lr = svm.SVC(kernel="poly") 
#mul_lr = Pipeline([("LR",  linear_model.LogisticRegression(multi_class='multinomial',  solver='newton-cg', max_iter=1000)), ("SVM", svm.SVC(kernel="linear"))]) 

In [15]:

for mno in range(len(models)): 
    mul_lr = models[mno] 
    mul_lr.fit(mainarray, train_y)
print("Accuracy:",mul_lr.score(mainarray,train_y)*100) 


Accuracy: 95.06346967559944


In [16]:
pickle.dump(mul_lr, open("./model.pkl", 'wb')) 
model=pickle.load(open('model.pkl','rb'))
testdata = pd.read_csv('/home/pragya/project/newenv/dataset/test dataset.csv') 

testdata = testdata.drop('Gender',1)
testdata = testdata.drop('Age',1)
test= testdata.values


In [17]:
'''for i in range(len(test)): 
        if test[i][0] == "Male":
            test[i][0] = 1 
        else: 
            test[i][0] = 0 '''

'for i in range(len(test)): \n        if test[i][0] == "Male":\n            test[i][0] = 1 \n        else: \n            test[i][0] = 0 '

In [18]:
df1=pd.DataFrame(test) 
testdf =df1[[0,1,2,3,4]] 
maintestarray=testdf.values 
print(maintestarray)


[[7 9 9 5 5]
 [5 4 5 2 4]
 [5 5 7 2 4]
 ...
 [7 5 6 2 7]
 [6 7 5 4 3]
 [5 7 3 5 6]]


In [19]:
y_pred = mul_lr.predict(maintestarray) 
print(maintestarray[0]) 
print(list(y_pred), df1[[5]].values)

[7 9 9 5 5]
['lively', 'dependable', 'serious', 'dependable', 'serious', 'serious', 'extraverted', 'dependable', 'responsible', 'extraverted', 'dependable', 'serious', 'extraverted', 'serious', 'serious', 'extraverted', 'extraverted', 'serious', 'serious', 'dependable', 'responsible', 'serious', 'responsible', 'lively', 'responsible', 'dependable', 'serious', 'serious', 'dependable', 'serious', 'lively', 'extraverted', 'serious', 'dependable', 'responsible', 'extraverted', 'responsible', 'serious', 'extraverted', 'dependable', 'lively', 'serious', 'lively', 'lively', 'dependable', 'responsible', 'lively', 'responsible', 'extraverted', 'extraverted', 'dependable', 'responsible', 'serious', 'extraverted', 'dependable', 'dependable', 'serious', 'dependable', 'responsible', 'serious', 'lively', 'lively', 'dependable', 'extraverted', 'extraverted', 'serious', 'responsible', 'dependable', 'serious', 'serious', 'extraverted', 'extraverted', 'extraverted', 'responsible', 'dependable', 'extrave

In [20]:

real = df1[[5]].values 
predicted = list(y_pred) 
error = 0 


In [21]:
for i in range(len(predicted)): 
    if (real[i][0] != predicted[i]): 
        error += 1 
    print(lables[mno]+":", ((len(predicted) - error)/len(predicted))*100) 
    for i in range(len(y_pred)) : 
        y_pred[i]=str((y_pred[i])) 


Decision Tree: 99.68253968253968
Decision Tree: 99.36507936507937
Decision Tree: 99.36507936507937
Decision Tree: 99.04761904761905
Decision Tree: 98.73015873015873
Decision Tree: 98.73015873015873
Decision Tree: 98.73015873015873
Decision Tree: 98.4126984126984
Decision Tree: 98.09523809523809
Decision Tree: 97.77777777777777
Decision Tree: 97.46031746031746
Decision Tree: 97.14285714285714
Decision Tree: 96.82539682539682
Decision Tree: 96.82539682539682
Decision Tree: 96.5079365079365
Decision Tree: 96.5079365079365
Decision Tree: 96.19047619047619
Decision Tree: 96.19047619047619
Decision Tree: 96.19047619047619
Decision Tree: 95.87301587301587
Decision Tree: 95.55555555555556
Decision Tree: 95.23809523809523
Decision Tree: 94.92063492063491
Decision Tree: 94.6031746031746
Decision Tree: 94.28571428571428
Decision Tree: 93.96825396825396
Decision Tree: 93.65079365079364
Decision Tree: 93.33333333333333
Decision Tree: 93.01587301587301
Decision Tree: 92.6984126984127
Decision Tree: 

In [22]:

#DF = pd.DataFrame(y_pred,columns=['Predicted Personality.']) 
#DF.index=DF.index+1 
#DF.index.names = ['Person No'] 
#DF.to_csv("output.csv") 


In [23]:
x= np.array(df.iloc[:, :5])
y= np.array(df.iloc[:,5])
#l=LabelEncoder()
#y=l.fit_transform(y)

